#!/bin/bash
# AI产业集群空间服务系统 - 快速启动命令

echo "======================================"
echo "AI产业集群空间服务系统"
echo "======================================"
echo ""
echo "启动命令:"
echo "  python start_services.py"
echo ""
echo "或使用一键启动:"
echo "  ./start_services.py"
echo ""
echo "启动后选择模式:"
echo "  1) 新架构 - 统一API网关 (推荐生产)"
echo "  2) 临时模式 - 旧架构 (推荐快速启动)"
echo "  3) 静态服务 - 仅前端 (推荐预览)"
echo ""
echo "详细文档:"
echo "  docs/启动指南.md"
echo ""
echo "======================================"